#!/usr/bin/env python3
import requests
import subprocess
import re

r = requests.get('http://beehive1.mcs.anl.gov/api/nodes')
nodes = r.json()

for node in nodes:
    nodeid = node['id']
    port = node['port']
    try:
        output = subprocess.check_output("ssh node{} 'echo OK; exit'".format(port), shell=True, stderr=subprocess.DEVNULL)
        assert re.search('OK', output.decode())
        priority = 5
        state = 'up'
    except:
        priority = 4
        state = 'down'

    print('<{}>{} {}'.format(priority, nodeid, state))
