#!/usr/bin/env python3
import requests
import sys
import json


r = requests.get('http://beehive1.mcs.anl.gov/api/nodes')

if r.status_code != 200:
    print('Could not get nodes.')
    sys.exit(1)

for node in r.json():
    result = {
        'id': node['id'][-12:].lower(),
        'name': node['name'],
        'description': node['description'],
        'location': node['location']
    }

    print(json.dumps(result), flush=True)
