#!/usr/bin/env python3
import requests
import sys


template = '''
id={id}
name={name}
description={description}
location={location}
port={port}
'''.strip()


def render(results):
    for result in results:
        yield template.format(**result)


query = '?' + '&'.join(sys.argv[1:])
r = requests.get('http://beehive1.mcs.anl.gov/api/nodes' + query)
print('\n\n'.join(render(r.json())))
